steps:
- name: 'golang:1.12-alpine'
  entrypoint: sh
  args:
  - '-c'
  - |
    apk add make bash git; \
    ls -al; \
    make ci-test
    make ci-build
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '-t'
  - 'gcr.io/bigreat/promtable:${_DOCKER_TAG_}'
  - '.'

substitutions:
  _DOCKER_TAG_: $BRANCH_NAME

images:
- 'gcr.io/bigreat/promtable:${_DOCKER_TAG_}'
