steps:
- name: 'golang:1.12-alpine'
  entrypoint: sh
  args:
  - '-c'
  - |
    apk add make bash git; \
    ls -al; \
    make ci-test; \
    make ci-build
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '-t'
  - 'gcr.io/pub-registry-chen-dev/promtable:${BRANCH_NAME}'
  - '.'

images:
- 'gcr.io/pub-registry-chen-dev/promtable:${BRANCH_NAME}'
