steps:
- name: 'golang:1.12-alpine'
  entrypoint: sh
  args:
  - '-c'
  - |
    apk add make bash; \
    go get -u github.com/kisielk/errcheck; \
    go get -u golang.org/x/lint/golint; \
    make ci-test; \
