[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "cloud.google.com/go"
  version = "0.36.0"

[[constraint]]
  name = "github.com/golang/snappy"
  version = "0.0.1"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.9.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"
