[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "cloud.google.com/go"
  revision = "de254f943f7bc67d8079839602828d8f512119ef"
  source = "github.com/uschen/google-cloud-go"

[[constraint]]
  name = "github.com/golang/snappy"
  version = "0.0.1"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.9.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/twmb/murmur3"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.2"
